#!/usr/bin/perl
use Apache::Htpasswd::Perishable;

my $password_file = '/usr/loca/apache/passwords/user.pass';

open(F,$password_file) or die "Could not open password file.";
my@users;
while(my $user = <F>){
  $user =~ s/^([^:])+:.*$/$1/;
  push @users, $user;
}
close F;

my $pass = Apache::Htpasswd::Perishable->new($password_file) or die
  "Could not open password file.";
foreach my $user ($users){
  $pass->
}



