#!/usr/bin/perl
use Apache::Htpasswd::Perishable;

my $password_file = '/usr/loca/apache/passwords/user.pass';

open() or die "";
my@users;
while(){}
close F;

my $pass = Apache::Htpasswd::Perishable->new() or die
  "";
foreach my $user (){}



